apiVersion: v1
description: helm chart for k8s control plane in k8s + cilium-operator
name: k8s-control-plane
keywords:
  - kubernetes
  - cilium-operator
version: 0.4.2
maintainers:
  - name: Patrik Majer
    email: patrik.majer@firma.seznam.cz

