{{- if and (.Values.operator.enabled) (.Values.operator.prometheus.enabled) (.Values.operator.prometheus.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator
  {{- if .Values.operator.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.operator.prometheus.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
{{- if .Values.operator.prometheus.serviceMonitor.interval }}
    interval: {{ .Values.operator.prometheus.serviceMonitor.interval }}
{{- end }}
{{- if .Values.operator.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.operator.prometheus.serviceMonitor.metricRelabelings | indent 6 }}
{{- end }}
{{- if .Values.operator.prometheus.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.operator.prometheus.serviceMonitor.relabelings | indent 6 }}
{{- end }}
    honorLabels: true
    path: /metrics
{{- end }}
