{{- if .Values.metricsHelper.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-sync-sa
data:
  sync-token.sh: |
    #!/bin/sh

    export KUBECONFIG=/kubeconfig/kubeconfig-service.yaml;

    kubectl version;

    #kubectl -n kube-system get secrets;

    TOKEN=$(kubectl -n kube-system get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='read-metrics')].data.token}")

    CACERT=$(kubectl -n kube-system get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='read-metrics')].data.ca\.crt}")

    echo $TOKEN > /metrics-sync-tokens/{{ .Release.Namespace }}-k3s-server-read-metrics-token

    #cat /metrics-sync-tokens/{{ .Release.Namespace }}-k3s-server-read-metrics-token

{{- end }}
