{{- if and (.Values.metricsHelper.enable) (.Values.metricsHelper.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-server-api-server
spec:
  selector:
    matchLabels:
      k8s-app: k3s-server
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: apiserver
      scheme: https
      tlsConfig:
        #caFile: "/path/to/the/ca/file"
        insecureSkipVerify: true
      bearerTokenFile: {{ .Values.metricsHelper.serviceMonitor.tokenFolder }}/{{ .Release.Namespace }}-k3s-server-read-metrics/token
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoints_name]
          action: drop
          regex: .*nodeport.*
        {{ if .Values.metricsHelper.serviceMonitor.clusterName }}
        - replacement: {{ .Values.metricsHelper.serviceMonitor.clusterName }}
          targetLabel: cluster
        {{ else }}
        - replacement: {{ .Release.Namespace }}
          targetLabel: cluster
        {{ end }}
{{- end }}
