{{- if .Values.server.serviceNodeport.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: k3s-server
  name: k3s-server-nodeport
spec:
  type: NodePort
  ports:
    - name: "apiserver"
      port: 6443
      targetPort: 6443
      nodePort: {{ .Values.server.serviceNodeport.portApiServer }}
  selector:
    k8s-app: k3s-server
{{- end }}
