apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k3s-docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k3s-docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - server
          env:
            - name: K3S_KUBECONFIG_MODE
              value: "666"
            - name: K3S_KUBECONFIG_OUTPUT
              value: /output/kubeconfig.yaml
            - name: K3S_TOKEN
              value: K3S_TOKEN
          image: rancher/k3s:latest
          name: server
          ports:
            - containerPort: 6443
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/rancher/k3s
              name: k3s-server
            - mountPath: /output
              name: server-claim1
            - mountPath: /run
              name: server-tmpfs0
            - mountPath: /var/run
              name: server-tmpfs1
      restartPolicy: Always
      volumes:
        - name: k3s-server
          persistentVolumeClaim:
            claimName: k3s-server
        - name: server-claim1
          persistentVolumeClaim:
            claimName: server-claim1
        - emptyDir:
            medium: Memory
          name: server-tmpfs0
        - emptyDir:
            medium: Memory
          name: server-tmpfs1
status: {}
