{{- if .Values.server.enabled -}}
{{- if .Values.server.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: k3s-server
  name: server-output-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: "{{ .Values.server.persistentVolume.size }}"
{{- end -}}
{{- end -}}
