{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: k3s-server
  name: k3s-server
spec:
  replicas: {{ .Values.server.replicas }}
  {{- with .Values.server.updateStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      k8s-app: k3s-server
  template:
    metadata:
      labels:
        k8s-app: k3s-server
    spec:
      containers:
        - args:
            - server
            - --flannel-backend=none
            - --disable-cloud-controller
            - --disable=traefik
            - --disable=metrics-server
          env:
            - name: K3S_KUBECONFIG_MODE
              value: "666"
            - name: K3S_KUBECONFIG_OUTPUT
              value: /output/kubeconfig.yaml
            - name: K3S_TOKEN
              value: "159182491624237"
          image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          name: k3s-server
          ports:
            - containerPort: 6443
          resources: {}
          volumeMounts:
            - name: k3s-server-datadir
              mountPath: /var/lib/rancher/k3s
            - name: server-output
              mountPath: /output
            - name: server-tmpfs0
              mountPath: /run
            - name: server-tmpfs1
              mountPath: /var/run
      restartPolicy: Always
      volumes:
        - name: k3s-server-datadir
          emptyDir: {}
        - name: server-output
          emptyDir: {}
        - name: server-tmpfs0
          emptyDir:
            medium: Memory
        - name: server-tmpfs1
          emptyDir:
            medium: Memory
{{- end }}
