{{- if .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: k3s-server
  name: server
spec:
  ports:
    - name: "6443"
      port: 6443
      targetPort: 6443
    - name: "metrics"
      port: 8080
      targetPort: 8080
    - name: "metrics2"
      port: 8081
      targetPort: 8081
  selector:
    k8s-app: k3s-server
{{- end }}
